---
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS INSTANCES
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


global_config:
  environment_name: cp4waiops
  cloud_platform: existing-ocp
  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS Pull Registires
  # --------------------------------------------------------------------------------------------------------------------------------------
  entitled_registry: cp.icr.io
  entitled_registry_user: cp
  catalog_image: icr.io/cpopen/ibm-operator-catalog:latest
  create_cards: true
  create_ocp_items: true


openshift:
- name: "mycluster"
  ocp_version: "4.10"
  cluster_name: "mycluster"
  domain_name: example.com
  openshift_storage:
  - storage_name: ibm-cloud-storage
    storage_type: custom
# Use file storate class provided as part of ROKS cluster
    ocp_storage_class_file: automatic
    ocp_storage_class_block: automatic
    #ocp_storage_class_file: ibmc-file-gold-gid
    #ocp_storage_class_block: ibmc-block-gold


cp4waiops:
- project: cp4waiops-addons
  instances:
  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS TURBONOMIC
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: cp4waiops-turbonomic
    kind: Turbonomic
    install: true
    turbo_version: 8.6.6
    
    # --------------------------------------------------------------------------------------------------------------------------------------
    # Storage Classes Override for this Instance (see comment below)
    # --------------------------------------------------------------------------------------------------------------------------------------
    #storage_class_file: automatic
    #storage_class_block: automatic

    
  - name: cp4waiops-turbonomic-demo-content
    kind: TurbonomicDemoContent
    install: true
    turbo_password: P4ssw0rd!
    # ---------------------------------------------------------------------
    # Create Demo User
    create_user: false
    demo_user: demo
    demo_password: P4ssw0rd!
    # ---------------------------------------------------------------------
    # Create Groups
    group_vcenter_vms: true
    group_robotshop: true
    group_licensing: true

    # ---------------------------------------------------------------------
    # Create Targets
    target_instana: true
    # ---------------------------------------------------------------------
    # Create Memory and CPU hogs
    resource_hogs: true
    # ---------------------------------------------------------------------
    # Create Metrics server, DIF integration and RobotShop BuisnessApp
    metrics_dif: true

    

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS USAGE
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS Storage Classes
# --------------------------------------------------------------------------------------------------------------------------------------

# Override the Storage Class auto detection (not_configured, ibmc-file-gold-gid, rook-cephfs, nfs-client, ...)
#storage_class_file: automatic
#storage_class_file: ibmc-file-gold-gid               # ROKS
#storage_class_file: ocs-storagecluster-cephfs        # ODF
#storage_class_file: ibmc-vpc-block-10iops-tier       # IBM VPC
#storage_class_file: rook-cephfs                      # FYRE
#storage_class_file: nfs-client                       # TEC

#storage_class_block: automatic
#storage_class_block: ibmc-block-gold                 # ROKS
#storage_class_block: ocs-storagecluster-ceph-rbd     # ODF
#storage_class_block: ibmc-vpc-block-10iops-tier      # IBM VPC
#storage_class_block: rook-cephfs                     # FYRE
#storage_class_block: nfs-client                      # TEC

