---
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS INSTANCES
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

cp4waiops:
- project: cp4waiops-addons
  instances:
  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS ARGOCD
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: cp4waiops-argoCD
    kind: GitOps
    install: true
    test: 1234

