---
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS INSTANCES
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

cp4waiops:
- project: cp4waiops-addons
  instances:
  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS ELK
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: cp4waiops-elk
    kind: ELK
    install: true


