---
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#         ________  __  ___     ___    ________
#        /  _/ __ )/  |/  /    /   |  /  _/ __ \____  _____
#        / // __  / /|_/ /    / /| |  / // / / / __ \/ ___/
#      _/ // /_/ / /  / /    / ___ |_/ // /_/ / /_/ (__  )
#     /___/_____/_/  /_/    /_/  |_/___/\____/ .___/____/
#                                           /_/
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4WAIOPS
#
#  CloudPak for Watson AIOps
#
#  ©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - openLDAP
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"

# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# INSTALL ADDONS
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Install OpenLDAP
- name: 📥  21_addons-ldap
  include_tasks: 21_addons-ldap.yaml
# Create Service Accoutn and USER
- name: 📥   22_addons-user
  include_tasks: 22_addons-user.yaml

# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# POSTINSTALL TASKS
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Register LDAP Users
- name: 📥  25-post-ldap-register
  include_tasks: 25-post-ldap-register.yaml
