#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#       __________  __ ___       _____    ________            
#      / ____/ __ \/ // / |     / /   |  /  _/ __ \____  _____
#     / /   / /_/ / // /| | /| / / /| |  / // / / / __ \/ ___/
#    / /___/ ____/__  __/ |/ |/ / ___ |_/ // /_/ / /_/ (__  ) 
#    \____/_/      /_/  |__/|__/_/  |_/___/\____/ .___/____/  
#                                              /_/            
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4WAIOPS
#
#  CloudPak for Watson AIOps
#
#  ©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"



# - name: Show Config
#   debug:
#     var: cp4waiops_cluster
- name: 🟡🟡🟡  Show Config File
  debug:
    var: all_config
    verbosity: 2

- name: 🛠️  Get Global Config
  set_fact: global_config={{ all_config.global_config | default([]) }}
- name: 🟡🟡🟡  Show Global Config
  debug:
    var: global_config
    verbosity: 1


- name: 🛠️  Get Openshift Config
  set_fact: _current_openshift_cluster={{ all_config.openshift | default([]) }}
- name: 🟡🟡🟡  Show Openshift Config
  debug:
    var: _current_openshift_cluster
    verbosity: 1




# Loop over all clusters
- name: MAIN LOOP   🚀 Deploy Cloud Pak for Watson AIOps Assets - Loop over Instances for {{current_cp4waiops_cluster.project}}
  include_role:
    name: cp4waiops-install-modules
  loop: "{{ current_cp4waiops_cluster.instances}}"
  loop_control:
    loop_var: current_cp4waiops_feature


