apiVersion: v1
kind: ServiceAccount
metadata:
  name: eda-admin
  namespace: eda
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cp4waiops-experimental-admin-crb
subjects:
  - kind: ServiceAccount
    name: eda-admin
    namespace: eda
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin